wavefrontHQ/wavefront-sdk-go

README.md
application/heartbeater.go
internal/lines.go
internal/proxy.go
senders/direct.go
senders/direct_test.go
senders/formatter.go
senders/formatter_test.go
senders/proxy.go
senders/proxy_test.go

Fix concurrency issues and other optimizations

---

internal/lines.go

This is the proposed fix for #51. By moving the `failures` and `throttled` fields to the top of the struct we can ensure they are 64-bit aligned.

Align LineHandler struct fields to allow atomic access

---

internal/lines.go
internal/reporter.go
senders/client.go
senders/client_factory.go
senders/client_factory_test.go
senders/client_test.go

This PR adds options for the constructor for `WavefrontSender` to specify tracing port and metrics port separately from the endpoint hostname so that metrics can be sent to the correct port even when using a wavefront-proxy's `customTracingListenerPorts`.

Support sending spans and metrics to different ports using the WavefrontSender

---

go.mod
go.sum

I'm not sure why upgrading the go version required these changes as forced by `go mod tidy`, but happy to get your feedback

Update go version, which forced me to run go mod tidy..

---

internal/registry.go
senders/client_factory.go
senders/client_factory_test.go
senders/client_test.go
senders/configs.go
senders/proxy.go
senders/proxy_test.go

Update newProxySender to take an additional setter with Otel tag set by
the Otel-Collector.

Allow for tagging internal SDK metrics

---

senders/client_factory.go
senders/client_factory_test.go

Fix senders.NewSender() for direct ingestion.

---

internal/reporter.go
internal/reporter_test.go
senders/client_factory.go
senders/client_factory_test.go

resolves: #108
This PR adds a "Path" field to the `configuration` struct so that we can stash the path component of a URL there and use it to correctly reconstruct a URL later.
I would be interested in suggestions about the `MetricsURL` and `TracesURL` methods; I think exporting these is a little bit unfortunate, but the url construction is important to test and is currently a little hard to exercise in a test because it's happening inside unexported functions. We could refactor to make this easier to test, but I didn't want to increase the scope of the PR for this fix.
This supports usecases where rather than talking to a WF instances or proxy directly, we are communicating through some sort of proxy that does path-based routing of our requests.
@keep94 @oppegard thanks in advance for …

bug: address parsing wavefront urls with a path component

---

senders/integration_test.go
senders/test_server_test.go

In the process of working on #109 , I was worried about not having automated end-to-end test coverage, and I thought that even a simple test against a local http server might make it easier to refactor the sdk internals with greater confidence.
@keep94 what do you think?
cc: @suprajanarasimhan @ktollivervmw

testing: add a basic integration test

---

senders/client.go
senders/client_multi.go
senders/client_noop.go

This is another way to ensure that we can add methods to Sender as non-breaking changes.  This works but it is weird because we declare a 9 method interface in GO, a language where interfaces with just 1 or 2 methods are common. Also, note that there is not a way to write examples for interface methods in GO. I think this is by design.
The up side to this solution is that it won't break most existing clients.

Make Sender so that it can't be implemented externally.

---

Makefile
scripts/godoc-install-hint.sh

this PR adds a `make godoc` command.
If godoc is not installed, it will print a hint about installing the godoc cli
If godoc is installed, it will run the godoc http server and print a link to go directly to the wavefront sdk package docs

add make godoc target so new contributors can easily review godoc

---

internal/reporter.go
internal/reporter_test.go
senders/client_factory.go
senders/client_factory_test.go
senders/example_newsender_options_test.go
senders/integration_test.go
senders/test_server_test.go

Related to https://github.com/wavefrontHQ/wavefront-sdk-go/issues/6.
This is an extension of PR #111, which I closed due to having introduced undesired merge commits in git history. 
**Detailed description:**
Make request timeout and TLS properties configurable. 
Add new configuration options to README.
Signed-off-by: Devon Warshaw <warshawd@vmware.com>
Signed-off-by: Jeanette Booher <jbooher@vmware.com>
Signed-off-by: Supraja Narasimhan <suprajan@vmware.com>

Make request timeout and TLS properties configurable.

---

senders/client.go
senders/client_factory.go
senders/client_factory_test.go
senders/example_newsender_options_test.go

see: /issues/121
I think we should keep the `FlushIntervalSeconds` version for now, but probably mark it as deprecated. I agree with @oppegard 's point in the linked issue that semantically it is better to express durations as `time.Duration` rather than as `int`s.

feat: allow configuring flush interval using time.Duration

---

senders/client_factory.go
senders/client_factory_test.go
senders/integration_test.go
senders/test_server_test.go

addresses #133 
This PR restores support for paths in URLs passed to the Wavefront sender.
* adds a top-level integration test for path support, so that it's less likely to break in the future
* makes several helper funcs internal
* moves sender package tests into sender package (so they can call non-public funcs)

fix: restore support for paths in URLs

---

.github/workflows/main.yml
go.mod

Our github action runs our tests across 3 versions of golang: (`1.16.x`,`1.17.x`, `1.18.x`). These versions are all considered unsupported according to Go's release policy:
https://go.dev/doc/devel/release#policy
This PR updates the matrix to include only the currently supported golang versions: `1.19.x` and `1.20.x`
#138 is currently failing because the new version of `stretchr/testify` uses a reflection API that doesn't exist in `1.16.x`.
Maybe there are good arguments to continue to support `1.18.x` or `1.17.x`, but I think dropping `1.16.x` now is the right call.

chore: update github action to reflect current supported golang versions

---

senders/example_newsender_proxy_test.go

docs: add an example of sending to a Wavefront proxy with custom ports

---

.golangci.yaml
internal/auth/csp/api_token_client.go
internal/auth/csp/client_credentials.go
internal/auth/csp/response.go
internal/histogram/formatter_test.go
senders/real_sender_test.go

this PR enables the `ineffassign` linter, and fixes existing ineffective assigns (mostly ignored errors)
It also extracts a common http response parsing helper method to remove some duplication (which also previously included an ineffective assign)

chore: fix ineffective assigns, enable ineffassign linter

---

.github/workflows/main.yml
RELEASING.md
ci/pipelines/osspi-wavefront-sdk-go/pipeline.yml

We recently switched our default branch from `master` to `main`. This PR changes our CI and documentation to reflect the new default branch.

chore: update pipelines, workflows, and documents to reflect switch to main as default branch

---

internal/reporter.go
internal/reporter_test.go
senders/configuration.go
senders/example_newsender_options_test.go
senders/integration_test.go
senders/new_sender.go
senders/new_sender_test.go
senders/option.go

related to https://github.com/influxdata/telegraf/issues/14090
This PR introduces a new `Option`, `HTTPClient`, allowing users to override the `*http.Client` used by the `Sender`.
This allows a variety of customization options, such as proxy settings, idle connection management, and TLS Options. It is intended to integrate well with Telegraf's http config, which can generate an `http.Client` from a standard `toml` configuration (https://github.com/influxdata/telegraf/blob/master/plugins/common/http/config.go)
This PR ~~reimplements the existing `Timeout` and `TLSConfig` options in terms of `configuration.HTTPClient`, and~~ eliminates the internal `NewClient` factory.
~~feedback request: the PR logs a warning if you try to use more than one of `Timeout`, `TLSConfig`, and `HTTPClient` for …

feat: add an option to set the http.Client for the Sender

---

internal/handler_factory.go
internal/lines.go
senders/new_sender.go
senders/option.go
senders/real_sender.go
senders/wavefront_sender_test.go

The `NewSender` function currently uses a pattern like this:
```
sender.pointHandler = newLineHandler(metricsReporter, cfg, internal.MetricFormat, "points", sender.internalRegistry)
sender.histoHandler = newLineHandler(metricsReporter, cfg, internal.HistogramFormat, "histograms", sender.internalRegistry)
sender.spanHandler = newLineHandler(tracesReporter, cfg, internal.TraceFormat, "spans", sender.internalRegistry)
sender.spanLogHandler = newLineHandler(tracesReporter, cfg, internal.SpanLogsFormat, "span_logs", sender.internalRegistry)
```
In this pattern, the caller must know that you send `points` with the `metricsReporter`, you use the `points` prefix, and you set the `MetricFormat`.
This PR moves this knowledge into dedicated factory functions for each line type, so that the factory …

chore: Sender refactor

---

internal/interfaces.go
internal/lines.go
internal/reporter.go
senders/integration_test.go
senders/live_test.go
senders/test_server_test.go

This refactor simplifies the `Reporter` interface by pushing a conditional from the caller into the `Report` method and eliminating `ReportEvent` from the interface.
* simplifies code at the call site
* makes the interface smaller
* applies [Tell, Don't Ask](https://martinfowler.com/bliki/TellDontAsk.html)

refactor: simplify Reporter interface
